language: java
jdk:
  - oraclejdk8
  - openjdk8
before_deploy:
- openssl aes-256-cbc -K $encrypted_1a824237c6f8_key -iv $encrypted_1a824237c6f8_iv
  -in .travis/keys.tar.enc -out .travis/keys.tar -d
- tar xvf .travis/keys.tar
env:
  global:
    secure:
deploy:
  provider: script
  script: bash scripts/deploy.sh $TRAVIS_TAG
  skip_cleanup: true # needed so that no "git stash" is executed, which would then remove the pgp keys extracted in before_deploy
  on:
    tags: true
    branch: master
